export interface DangersAndUsefulPools {
  iriomoteCat: Record<number, string[]>;
  radish: Record<number, string[]>;
  rolowayMonkey: string[];
  goldenTamarin: string[];
  bayCat: string[];
}

export const DANGERS_AND_USEFUL_POOLS: DangersAndUsefulPools = {
  iriomoteCat: {
    1: [
      'Ant',
      'Mosquito',
      'Cricket',
      'Moth',
      'Beetle',
      'Chihuahua',
      'Cockroach',
      'Hummingbird',
      'Frilled Dragon',
      'Farmer Mouse',
      'Budgie',
      'Groundhog',
      'Cone Snail',
      'Goose',
      'Barghest',
      'Tsuchinoko',
      'Alchemedes',
      'Bunyip',
      'Sneaky Egg',
      'Ethiopian Wolf',
      'African Wild Dog',
      'Volcano Snail',
      'Pygmy Seahorse',
      'Nudibranch',
    ],
    2: [
      'Crab',
      'Hedgehog',
      'Flamingo',
      'Spider',
      'Robin',
      'Beluga Sturgeon',
      'Stork',
      'Bass',
      'Panda',
      'Seahorse',
      'Roadrunner',
      'Mink',
      'Meerkat',
      'Black Necked Stilt',
      'Sea Urchin',
      'Honduran White Bat',
      'Frost Wolf',
      'Ogopogo',
      'Thunderbird',
      'Bigfoot',
      'Takhi',
      'White-Bellied Heron',
      'Taita Shrew',
      'Nightcrawler',
      'Pink Robin',
      'Fruit Fly',
      'Olm',
      'Tadpole',
      'Thorny Dragon',
    ],
    3: [
      'Dodo',
      'Dolphin',
      'Sheep',
      'Hoopoe Bird',
      'Pug',
      'Anteater',
      'Eel',
      'Bear',
      'Farmer Pig',
      'Brazillian Treehopper',
      'Flea',
      'Weasel',
      'Osprey',
      'Blue Dragon',
      'Betta Fish',
      'Skeleton Dog',
      'Mandrake',
      'Fur-Bearing Trout',
      'Mana Hound',
      'Roloway Monkey',
      'Amami Rabbit',
      'Hirola',
      'Tucuxi',
      'Tree Kangaroo',
      'Slime',
      'Dimetrodon',
      'Gerenuk',
      'Pangasius',
      'Vampire Parrot',
    ],
  },
  radish: {
    1: ['Walnut', 'Honey', 'Egg', 'Strawberry'],
    2: [
      'Meat Bone',
      'Lime',
      'Caramel',
      'Bok Choy',
      'Fairy Dust',
      'Faint Bread',
      'Cod Roe',
    ],
    3: ['Garlic', 'Squash', 'Seaweed', 'Fig', 'Brussels Sprout'],
    4: [
      'Fortune Cookie',
      'Salt',
      'Baguette',
      'Cheese',
      'Banana',
      'Bread',
      'Ambrosia',
    ],
    5: ['Chili', 'Lemon', 'Pepper', 'Durian', 'Honeydew Melon', 'Easter Egg'],
    6: [
      'Steak',
      'Melon',
      'Pita Bread',
      'Tomato',
      'Yggdrasil Fruit',
      'Popcorn',
      'White Okra',
    ],
  },
  rolowayMonkey: [
    'Beluga Sturgeon',
    'Bigfoot',
    'Black Necked Stilt',
    'Dove',
    'Dung Beetle',
    'Flamingo',
    'Frost Wolf',
    'Gargoyle',
    'Hedgehog',
    'Mandrill',
    'Nightcrawler',
    'Olm',
    'Rat',
    'Sea Urchin',
    'Spider',
    'Squid',
    'Stork',
    'Takhi',
    'Thorny Dragon',
    'Anteater',
    'Baby Urchin',
    'Badger',
    'Bear',
    'Calygreyhound',
    'Dugong',
    'Flea',
    'Fur-Bearing Trout',
    'Hirola',
    'Hoopoe Bird',
    'Jewel Caterpillar',
    'Mole',
    'Osprey',
    'Pangolin',
    'Patagonian Mara',
    'Quetzalcoatlus',
    'Sheep',
    'Skeleton Dog',
    'Slime',
    'Surgeon Fish',
    'Tucuxi',
    'Tuna',
    'Weasel',
  ],
  goldenTamarin: [
    'Skunk',
    'Doberman',
    'Hawk',
    'Humphead Wrasse',
    'Tasmanian Devil',
    'Lynx',
    'Crocodile',
    'Swordfish',
    'Red Dragon',
    'Werewolf',
    'Snow Leopard',
    'Tarantula Hawk',
  ],
  bayCat: [
    'Anubis',
    'Caterpillar',
    'Doberman',
    'Fossa',
    'Goblin Shark',
    'Hawk',
    'Hoatzin',
    'Humphead Wrasse',
    'Kraken',
    'Leafy Sea Dragon',
    'Lynx',
    'Platybelodon',
    'Red Lipped Batfish',
    'Roc',
    "Ruspoli's Turaco",
    'Skunk',
    'Tasmanian Devil',
    'Whale',
  ],
};
