export interface DangersAndUsefulPools {
  iriomoteCat: Record<number, string[]>;
  radish: Record<number, string[]>;
  rolowayMonkey: string[];
  goldenTamarin: string[];
  bayCat: string[];
}

export const DANGERS_AND_USEFUL_POOLS: DangersAndUsefulPools = {
  iriomoteCat: {
    1: [
      'Ant',
      'Mosquito',
      'Cricket',
      'Moth',
      'Beetle',
      'Chihuahua',
      'Cockroach',
      'Hummingbird',
      'Frilled Dragon',
      'Farmer Mouse',
      'Budgie',
      'Groundhog',
      'Cone Snail',
      'Goose',
      'Barghest',
      'Tsuchinoko',
      'Alchemedes',
      'Bunyip',
      'Sneaky Egg',
      'Ethiopian Wolf',
      'African Wild Dog',
      'Volcano Snail',
      'Pygmy Seahorse',
      'Nudibranch',
    ],
    2: [
      'Crab',
      'Hedgehog',
      'Flamingo',
      'Spider',
      'Robin',
      'Beluga Sturgeon',
      'Stork',
      'Bass',
      'Panda',
      'Seahorse',
      'Roadrunner',
      'Mink',
      'Meerkat',
      'Black Necked Stilt',
      'Sea Urchin',
      'Honduran White Bat',
      'Frost Wolf',
      'Ogopogo',
      'Thunderbird',
      'Bigfoot',
      'Takhi',
      'White-Bellied Heron',
      'Taita Shrew',
      'Nightcrawler',
      'Pink Robin',
      'Fruit Fly',
      'Olm',
      'Tadpole',
      'Thorny Dragon',
    ],
    3: [
      'Dodo',
      'Dolphin',
      'Sheep',
      'Hoopoe Bird',
      'Pug',
      'Anteater',
      'Eel',
      'Bear',
      'Farmer Pig',
      'Brazillian Treehopper',
      'Flea',
      'Weasel',
      'Osprey',
      'Blue Dragon',
      'Betta Fish',
      'Skeleton Dog',
      'Mandrake',
      'Fur-Bearing Trout',
      'Mana Hound',
      'Roloway Monkey',
      'Amami Rabbit',
      'Hirola',
      'Tucuxi',
      'Tree Kangaroo',
      'Slime',
      'Dimetrodon',
      'Gerenuk',
      'Pangasius',
      'Vampire Parrot',
    ],
  },
  radish: {
    1: ['Walnut', 'Honey', 'Egg', 'Strawberry'],
    2: [
      'Meat Bone',
      'Lime',
      'Caramel',
      'Bok Choy',
      'Fairy Dust',
      'Faint Bread',
      'Cod Roe',
    ],
    3: ['Garlic', 'Squash', 'Seaweed', 'Fig', 'Brussels Sprout'],
    4: ['Fortune Cookie', 'Salt', 'Baguette', 'Cheese', 'Banana', 'Ambrosia'],
    5: ['Chili', 'Lemon', 'Pepper', 'Durian', 'Honeydew Melon', 'Easter Egg'],
    6: [
      'Steak',
      'Melon',
      'Pita Bread',
      'Tomato',
      'Yggdrasil Fruit',
      'Popcorn',
      'White Okra',
    ],
  },
  rolowayMonkey: ['Peacock', 'Camel', 'Porcupine', 'Lizard', 'Guineafowl'],
  goldenTamarin: [
    'Crocodile',
    'Tarantula Hawk',
    'Red Dragon',
    'Werewolf',
    'Snow Leopard',
    'Sea Cucumber',
  ],
  bayCat: [
    'Skunk',
    'Fossa',
    'Hawk',
    'Lynx',
    'Platybelodon',
    'Kraken',
    'Tasmanian Devil',
    'Humphead Wrasse',
  ],
};
