import type { TeamPreset } from './team-presets.service';

export function getShoggothDefaultTeams(): TeamPreset[] {
  return [
    {
      id: 'default-shoggoths-return',
      name: "Shoggoth's Return",
      createdAt: Date.now(),
      toyName: 'Tinder Box',
      toyLevel: 3,
      rollAmount: 14,
      pets: [
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Nessie',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Highland Cow',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Sabertooth Tiger',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 50,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Unicorn',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Hydra',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
      ],
    },
    {
      id: 'default-shoggoth',
      name: 'Shoggoth',
      createdAt: Date.now(),
      toyName: 'Tinder Box',
      toyLevel: 3,
      rollAmount: 14,
      pets: [
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Nessie',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Highland Cow',
          attack: 50,
          health: 50,
          exp: 5,
          equipment: { name: 'White Okra' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Sabertooth Tiger',
          attack: 50,
          health: 50,
          exp: 5,
          equipment: { name: 'White Okra' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          battlesFought: 0,
          timesHurt: 50,
          equipmentUses: null,
        },
        {
          name: 'Marine Iguana',
          attack: 50,
          health: 50,
          exp: 5,
          equipment: { name: 'White Okra' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Hydra',
          attack: 50,
          health: 50,
          exp: 5,
          equipment: { name: 'White Okra' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
      ],
    },
  ];
}
