import type { TeamPreset } from './team-presets.service';

type TeamPresetPet = TeamPreset['pets'][number];

export function getDefaultTeams(): TeamPreset[] {
  return [
    {
      id: 'default-max-damage',
      name: '1000 Mana',
      createdAt: Date.now(),
      toyName: 'Nutcracker',
      toyLevel: 3,
      pets: Array.from({ length: 5 }, (): TeamPresetPet => ({
        name: 'Sea Serpent',
        attack: 50,
        health: 50,
        exp: 5,
        equipment: { name: 'Coconut' },
        belugaSwallowedPet: null,
        sarcasticFringeheadSwallowedPet: null,
        mana: 50,
        triggersConsumed: 0,
        abominationSwallowedPet1: null,
        abominationSwallowedPet2: null,
        abominationSwallowedPet3: null,
        abominationSwallowedPet1TimesHurt: 0,
        abominationSwallowedPet2TimesHurt: 0,
        abominationSwallowedPet3TimesHurt: 0,
        battlesFought: 0,
        timesHurt: 0,
        equipmentUses: null,
      })),
    },
    {
      id: 'default-great-six',
      name: 'The Great Six',
      createdAt: Date.now(),
      toyName: 'Evil Book',
      toyLevel: 3,
      pets: Array.from({ length: 5 }, (): TeamPresetPet => ({
        name: 'Beluga Whale',
        attack: 50,
        health: 50,
        exp: 5,
        equipment: { name: 'White Okra' },
        belugaSwallowedPet: 'Great One',
        sarcasticFringeheadSwallowedPet: null,
        mana: 50,
        triggersConsumed: 0,
        abominationSwallowedPet1: null,
        abominationSwallowedPet2: null,
        abominationSwallowedPet3: null,
        abominationSwallowedPet1TimesHurt: 0,
        abominationSwallowedPet2TimesHurt: 0,
        abominationSwallowedPet3TimesHurt: 0,
        battlesFought: 0,
        timesHurt: 0,
        equipmentUses: null,
      })),
    },
    {
      id: 'default-ability-removal',
      name: 'Orca Scam',
      createdAt: Date.now(),
      playerToyName: 'Pandoras Box',
      playerToyLevel: 1,
      opponentToyName: null,
      opponentToyLevel: 1,
      playerHardToy: null,
      playerHardToyLevel: 1,
      opponentHardToy: null,
      opponentHardToyLevel: 1,
      turn: 11,
      playerGoldSpent: 10,
      opponentGoldSpent: 10,
      allPets: true,
      tokenPets: true,
      komodoShuffle: false,
      mana: true,
      triggersConsumed: false,
      changeEquipmentUses: false,
      playerRollAmount: 3,
      opponentRollAmount: 1,
      playerLevel3Sold: 0,
      opponentLevel3Sold: 0,
      playerSummonedAmount: 0,
      opponentSummonedAmount: 0,
      playerTransformationAmount: 100,
      opponentTransformationAmount: 100,
      pets: [
        {
          name: 'Giant Pangasius',
          attack: 49,
          health: 1,
          exp: 1,
          equipment: null,
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          abominationSwallowedPet1Level: 1,
          abominationSwallowedPet2Level: 1,
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 1,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Orca',
          abominationSwallowedPet2: 'Behemoth',
          abominationSwallowedPet3: 'Rat',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 50,
          health: 1,
          exp: 5,
          equipment: { name: 'Silly' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Rat',
          abominationSwallowedPet2: 'Phoenix',
          abominationSwallowedPet3: 'Giant Pangasius',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 1,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet2: 'Rat',
          abominationSwallowedPet3: 'Albatross',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Cashew Nut' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet2: 'Panther',
          abominationSwallowedPet3: 'Guineafowl',
          abominationSwallowedPet1Level: 1,
          abominationSwallowedPet2Level: 1,
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
      ],
    },
    {
      id: 'default-sob-snipes',
      name: 'SoB Snipes',
      createdAt: Date.now(),
      toyName: 'Nutcracker',
      toyLevel: 3,
      pets: Array.from({ length: 5 }, (): TeamPresetPet => ({
        name: 'Leopard',
        attack: 50,
        health: 50,
        exp: 5,
        equipment: { name: 'Churros' },
        belugaSwallowedPet: null,
        sarcasticFringeheadSwallowedPet: null,
        mana: 50,
        triggersConsumed: 0,
        abominationSwallowedPet1: null,
        abominationSwallowedPet2: null,
        abominationSwallowedPet3: null,
        battlesFought: 0,
        timesHurt: 0,
        equipmentUses: null,
      })),
    },
    {
      id: 'default-infinite-damage',
      name: 'Infinite Damage',
      createdAt: Date.now(),
      toyName: 'Nutcracker',
      toyLevel: 1,
      rollAmount: 47,
      transformationAmount: 200,
      pets: [
        {
          name: 'Giant Pangasius',
          attack: 50,
          health: 1,
          exp: 5,
          equipment: { name: 'Mushroom' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Beluga Whale',
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet3BelugaSwallowedPet: 'Giant Pangasius',
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Cashew Nut' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Beluga Whale',
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet3BelugaSwallowedPet: 'Nessie',
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Sabertooth Tiger',
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 25,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2: 'Leopard',
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3: 'Beluga Whale',
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet3BelugaSwallowedPet: 'Slug',
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
      ],
    },
    {
      id: 'default-layers',
      name: 'Layers',
      createdAt: Date.now(),
      playerToyName: 'Nutcracker',
      playerToyLevel: 3,
      opponentToyName: 'Nutcracker',
      opponentToyLevel: 3,
      playerHardToy: null,
      playerHardToyLevel: 1,
      opponentHardToy: null,
      opponentHardToyLevel: 1,
      turn: 13,
      playerGoldSpent: 13,
      opponentGoldSpent: 13,
      allPets: true,
      tokenPets: true,
      komodoShuffle: false,
      mana: true,
      triggersConsumed: false,
      changeEquipmentUses: false,
      playerRollAmount: 1000,
      opponentRollAmount: 1000,
      playerLevel3Sold: 1000,
      opponentLevel3Sold: 1000,
      playerSummonedAmount: 1000,
      opponentSummonedAmount: 1000,
      playerTransformationAmount: 1000,
      opponentTransformationAmount: 1000,
      pets: [
        {
          name: 'Giant Pangasius',
          attack: 50,
          health: 1,
          exp: 5,
          equipment: { name: 'Mushroom' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: null,
          abominationSwallowedPet2: null,
          abominationSwallowedPet3: null,
          abominationSwallowedPet1Level: 1,
          abominationSwallowedPet2Level: 1,
          abominationSwallowedPet3Level: 1,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 0,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet2: 'Rat',
          abominationSwallowedPet3: 'Sabertooth Tiger',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 50,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Cashew Nut' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet2: 'Guineafowl',
          abominationSwallowedPet3: 'Vaquita',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 1,
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 50,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: 1,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet2: 'Rat',
          abominationSwallowedPet3: 'Vaquita',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 50,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: 1,
        },
        {
          name: 'Abomination',
          attack: 100,
          health: 100,
          exp: 5,
          equipment: { name: 'Churros' },
          belugaSwallowedPet: null,
          sarcasticFringeheadSwallowedPet: null,
          mana: 50,
          triggersConsumed: 0,
          abominationSwallowedPet1: 'Behemoth',
          abominationSwallowedPet2: 'Rat',
          abominationSwallowedPet3: 'Sabertooth Tiger',
          abominationSwallowedPet1Level: 3,
          abominationSwallowedPet2Level: 3,
          abominationSwallowedPet3Level: 3,
          abominationSwallowedPet1TimesHurt: 0,
          abominationSwallowedPet2TimesHurt: 0,
          abominationSwallowedPet3TimesHurt: 50,
          battlesFought: 0,
          timesHurt: 0,
          equipmentUses: null,
        },
      ],
    },
  ];
}
